demovibes/demovibes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from webview.views import log_out


urlpatterns = [
    path("", RedirectView.as_view(url="/demovibes/")),
    path("admin/", admin.site.urls),
    path("accounts/", include("registration.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/logout/", log_out, name="log_out"),
    path("demovibes/", include("webview.urls")),
    path("forum/", include("forum.urls")),
    path("search/", include("search.urls")),
    # path("", 'django.views.generic.simple.redirect_to', {'url': '/static/biebervibes/'}),  # April 1st 2015
    # ~ path("accounts/profile/", RedirectView.as_view(url='/demovibes/')),
    # ~ path("openid/', include('openid_provider.urls')),
]

# Only use this under development! Only for serving media files with dev server!
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demovibes/forum/urls.py
from django.urls import path
from . import views
from .feeds import RssForumFeed, AtomForumFeed


feed_dict = {"rss": RssForumFeed, "atom": AtomForumFeed}

app_name = "forum"
urlpatterns = [
    path("", views.ForumsView.as_view(), name="index"),
    path("thread/<int:thread>/", views.thread, name="view_thread"),
    path("edit/<int:post_id>/", views.edit),
    path("subscriptions/", views.updatesubs, name="subscriptions"),
    path("<slug:slug>/", views.forum, name="thread_list"),
    path("<path:path>/<slug:slug>/", views.forum, name="subforum_thread_list"),
    # path("(?P<url>(rss|atom).*)/", Feed(), {'feed_dict': feed_dict}),
]

demovibes/webview/models.py
import datetime
from io import StringIO
import json
import logging
import random
import os.path
import xml.dom.minidom
import urllib

from django.conf import settings
from django.contrib.auth.models import Group as UserGroup, User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.sites.models import Site
from django.core.cache import cache
from django.core.files.uploadedfile import SimpleUploadedFile
from django.core.mail import EmailMessage
from django.db import models
from django.db.models import GenericIPAddressField
from django.db.models.signals import post_save, pre_save
from django.template import Context, loader
from django.template.defaultfilters import striptags
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from PIL import Image

import prelisten
from tagging import registry as tagging
from ip2cc import ip2cc


class TimeDelta(datetime.timedelta):
    def total_seconds(self):
        return self.seconds + self.days * 24 * 3600

    def to_string(self):
        s = self.total_seconds()
        padding = ""
        if s < 0:
            s = s * -1
            padding = "-"
        hours, remainder = divmod(s, 3600)
        minutes, seconds = divmod(remainder, 60)
        time1 = "%02d:%02d" % (minutes, seconds)
        if hours:
            return padding + "%s:" % hours + time1
        return padding + time1


log = logging.getLogger("dv.webview.models")

CHEROKEE_SECRET = getattr(settings, "CHEROKEE_SECRET_DOWNLOAD_KEY", "")
CHEROKEE_PATH = getattr(settings, "CHEROKEE_SECRET_DOWNLOAD_PATH", "")
CHEROKEE_REGEX = getattr(settings, "CHEROKEE_SECRET_DOWNLOAD_REGEX", "")
CHEROKEE_LIMIT = getattr(settings, "CHEROKEE_SECRET_DOWNLOAD_LIMIT", "")
CHEROKEE_LIMIT_URL = getattr(settings, "CHEROKEE_SECRET_DOWNLOAD_LIMIT_URL", "")

NEWUSER_MUTE_TIME = getattr(settings, "NEW_USER_MUTE_TIME", None)

SELFVOTE_DISABLED = getattr(settings, "SONG_SELFVOTE_DISABLED", False)
SONG_LOCKTIME_FUNCTION = getattr(settings, "SONG_LOCKTIME_FUNCTION", None)


def get_now_playing_song(create_new=False):
    queueobj = cache.get("nowplaysong")
    if not queueobj or create_new:
        try:
            timelimit = datetime.datetime.now() - datetime.timedelta(hours=6)

            queueobj = (
                Queue.objects.select_related(depth=3)
                .filter(played=True)
                .filter(time_played__gt=timelimit)
                .order_by("-time_played")[0]
            )
            log.debug("Checking now playing song : Time limit is %s", timelimit)
        except:
            log.info("Could not find now_playing")
            return False
        cache.set("nowplaysong", queueobj, 300)
    return queueobj


if getattr(settings, "LOOKUP_COUNTRY", True):
    ipdb = os.path.join(settings.SITE_ROOT, "ipcountry.db")
    if not os.path.exists(ipdb):
        log.info("IP2Country DB not found, creating new")
        from ip2cc import update as ip2ccupdate

        ip2ccupdate.create_file(ipdb)

uwsgi_event_server = getattr(settings, "UWSGI_EVENT_SERVER", False)
nodejs_event_server = getattr(settings, "NODEJS_EVENT_SERVER", False)

if uwsgi_event_server:
    uwsgi_event_server_http = getattr(settings, "UWSGI_EVENT_SERVER_HTTP", False)
    try:
        import uwsgi
    except:
        import pickle

        uwsgi_event_server = "HTTP"

if nodejs_event_server:
    import pika

    connection = pika.AsyncoreConnection(pika.ConnectionParameters(host="localhost"))
    channel = connection.channel()

    channel.exchange_declare(exchange="events", type="fanout")


def send_notification(message, user, category=0):
    d = {
        "message": message,
        "category": category,
    }
    data = json.dumps(d)
    add_event("msg:%s" % data, user)


def add_event(event=None, user=None, eventlist=[], metadata={}):
    """
    Add event(s) to the event handler(s)

    Keywords:
    event -- string that will be sent to clients
    user -- optional -- User to receive the event
    eventlist -- List of event strings to process
    metadata -- Optional metadata to send along

    Either event or eventlist must be supplied
    """

    cache.delete("curr_event")

    if not event and not eventlist:
        return False

    if event:
        eventlist = [event]

    for event in eventlist:
        ae = AjaxEvent.objects.create(event=event, user=user)

    if nodejs_event_server:
        for x in eventlist:
            e = {
                "event": x,
                "user": user and user.id or None,
                "metadata": metadata,
            }
            e = json.dumps(e)
            channel.basic_publish(exchange="events", routing_key="", body=e)

    if uwsgi_event_server:
        R = AjaxEvent.objects.order_by("-id")[
            :20
        ]  # Should have time based limit here..
        R = [(x.id, x.event, x.user and x.user.id or "N") for x in R]
        data = (R, ae.id)
        if uwsgi_event_server:
            if uwsgi_event_server == "HTTP":
                data = {"data": pickle.dumps(data)}
                data = urllib.urlencode(data)
                log.debug("Event data via http: %s" % data)
                url = (
                    uwsgi_event_server_http
                    or "http://127.0.0.1/demovibes/ajax/monitor/new/"
                )
                try:
                    r = urllib.urlopen(url, data)
                except:
                    return False
                return r
            else:
                uwsgi.send_uwsgi_message(
                    uwsgi_event_server[0], uwsgi_event_server[1], 33, 17, data, 30
                )


from webview.managers import LockingManager, ActiveSongManager

# Create your models here.

# Used for artist / song listing
alphalist = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "-",
]


class Group(models.Model):
    STATUS_CHOICES = (
        ("A", "Active"),
        ("I", "Inactive"),
        ("D", "Dupe"),
        ("U", "Uploaded"),
        ("R", "Rejected"),
    )

    created_by = models.ForeignKey(
        User,
        null=True,
        blank=True,
        related_name="group_createdby",
        on_delete=models.SET_NULL,
    )
    found_date = models.DateField(
        verbose_name="Found Date",
        help_text="Date this group was formed (YYYY-MM-DD)",
        null=True,
        blank=True,
    )
    group_icon = models.ImageField(
        help_text="Group Icon (Shows instead of default icon)",
        upload_to="groups/icons",
        blank=True,
        null=True,
    )
    group_logo = models.ImageField(
        help_text="Logo/Pic Of This Group",
        upload_to="groups",
        blank=True,
        null=True,
    )
    info = models.TextField(
        blank=True,
        verbose_name="Group Info",
        help_text="Additional information on this group. No HTML.",
    )
    last_updated = models.DateTimeField(editable=False, blank=True, null=True)
    name = models.CharField(
        max_length=80,
        unique=True,
        db_index=True,
        verbose_name="* Name",
        help_text="The name of this group as you want it to appear.",
    )
    pouetid = models.IntegerField(
        verbose_name="Pouet ID",
        help_text="If this group has a Pouet entry, enter the ID number here - See http://www.pouet.net",
        blank=True,
        null=True,
    )
    startswith = models.CharField(max_length=1, editable=False, db_index=True)
    status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, default="A", db_index=True
    )
    webpage = models.URLField(
        blank=True,
        verbose_name="Website",
        help_text="Add the website address for this group, if one exists.",
    )
    wiki_link = models.URLField(
        blank=True, help_text="URL to wikipedia entry (if available)"
    )

    links = GenericRelation("GenericLink")

    def log(self, user, message):
        return ObjectLog.objects.create(obj=self, user=user, text=message)

    def get_logs(self):
        obj_type = ContentType.objects.get_for_model(self)
        return ObjectLog.objects.filter(content_type__pk=obj_type.id, object_id=self.id)

    def get_active_links(self):
        """
        Return all active generic links
        """
        return self.links.filter(status=0)

    def __str__(self):
        return self.name

    def get_songs(self):
        meta = Song.objects.filter(songmetadata__active=True, songmetadata__groups=self)
        return meta

    class Meta:
        ordering = ["name"]

    def save(self, *args, **kwargs):
        S = self.name[0].lower()
        if S not in alphalist:
            S = "#"
        self.startswith = S
        self.last_updated = datetime.datetime.now()
        return super(Group, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("webview:group", args=[str(self.id)])


class GenericBaseLink(models.Model):
    name = models.CharField(max_length=20)
    link = models.CharField(max_length=200, help_text="%linkval% for Link Value")
    description = models.TextField(blank=True)
    icon = models.ImageField(upload_to="linkicons", blank=True, null=True)
    inputinfo = models.TextField(blank=True)
    regex = models.TextField(help_text="Regex to check input value")
    LINKTYPE = (
        ("A", "Artists"),
        ("U", "Users"),
        ("S", "Songs"),
        ("G", "Groups"),

demovibes/templates/base/base.html
{% import "macro/display.html" as display %}
{% extends "base/base_skeleton.html" %}

{% block content %}
  <div id="sidebar">
    <div id="sitemenu">
      <h3>{{ gettext("Welcome") }}, {% if user.is_authenticated %}{{ user }}{% else %}{{ gettext("Visitor") }}{% endif %}!</h3>
      {% block sidebar %}
      <ul class="menulist">
        <li id="home"><a href="{{ url('webview:root') }}">{{ gettext("Home") }}</a></li>
        <li id="forum"><a href="{{ url('forum:index') }}">{{ gettext("Forum") }}</a></li>
        <li id="songs"><a href="{{ url('webview:songs') }}">{{ gettext("Songs") }}</a></li>
        <li id="song-source"><a href="{{ url('webview:sources') }}">{{ gettext("Sources") }}</a></li>
        <li id="song-platform"><a href="{{ url('webview:platforms') }}">{{ gettext("Platforms") }}</a></li>
        <li id="artists"><a href="{{ url('webview:artists') }}">{{ gettext("Artists") }}</a></li>
        <li id="groups"><a href="{{ url('webview:groups') }}">{{ gettext("Groups") }}</a></li>
        <li id="labels"><a href="{{ url('webview:labels') }}">{{ gettext("Labels") }}</a></li>
        <li id="compilations"><a href="{{ url('webview:compilations') }}">{{ gettext("Compilations") }}</a></li>
        <li id="screenshots"><a href="{{ url('webview:screenshots') }}">{{ gettext("Images") }}</a></li>
        <li id="licenses"><a href="{{ url('webview:licenses') }}">{{ gettext("Licenses") }}</a></li>
        {% if not user.is_authenticated or user.userprofile.use_tags %}
        <li id="tagcloud"><a href="{{ url('webview:tagcloud') }}">{{ gettext("Tag cloud") }}</a></li>
        {% endif %}
        <li id="statistics"><a href="{{ url('webview:stats-index') }}">{{ gettext("Statistics") }}</a></li>
        <li>&nbsp;</li>
        <li id="menuqueue"><a href="{{ url('webview:queue') }}">{{ gettext("Queue") }}</a></li>
        <li>&nbsp;</li>
        <li id="search"><a href="{{ url('s-all') }}">{{ gettext("Search") }}</a></li>
        <li id="recent"><a href="{{ url('webview:recent') }}">{{ gettext("New Uploads") }}</a></li>
        <li id="recentchanges"><a href="{{ url('webview:updates') }}">{{ gettext("Recent Updates") }}</a></li>
        <li>&nbsp;</li>
        <li id="faq"><a href="{{ url('webview:faq') }}">{{ gettext("FAQ") }}</a></li>
        <li id="links"><a href="{{ url('webview:links') }}">{{ gettext("Links") }}</a></li>
        <li id="chat"><a href="{{ url('webview:chat') }}">{{ gettext("Simple Chat") }}</a></li>
      </ul>
      {% endblock %}
    </div>
    <div id="menuoneliner">
      <h3>{{ gettext("Infamous OneLiner") }}</h3>
      {% if user.is_authenticated %}
      {% include "webview/oneliner_form.html" %}
      {% endif %}
      <div id="oneliner" data-name="oneliner">
        {%- for line in dv.get_oneliner() -%}
        <p class="onelinermsg">
          <span class="onelinerpre">
          {{ display.user(line.user) }}
            <span class="onelinertime">(<span class="tzinfo">{{ line.added|time("H:i:s") }}</span>)</span>
          </span>
          <br />
          <span class="onelinertext">{{ display.format_oneliner(line) }}</span>
        </p>
        {%- endfor -%}
      </div>
      <a href="{{ url('webview:oneliner') }}">{{ gettext("Oneliner History") }}</a>
    </div>

    <div id="menuonline">
      <h3>{{ gettext("Who's Online?") }}</h3>
      <div id="whosonlinenicks">{{ dv.get_online_users() }}</div>
    </div>
  </div>

  <div id="rightside">
    <div id="usermenu">
      <h3>{{ gettext("User Menu") }}</h3>
      <div class="message-display-settings">Notification settings</div>
      <ul class="menulist">
        {% if user.is_authenticated %}
        <li id="profile"><a href="{{ url('webview:my_profile') }}">{{ gettext("Edit My Profile") }}</a></li>
        <li id="favorites"><a href="{{ url('webview:favorites') }}">{{ gettext("My Favourites") }}</a></li>
        <li id="inbox"><a href="{{ url('webview:inbox') }}">{{ gettext("My Inbox") }}</a> {{ dv.get_unread_count(user) }}</li>
        <li id="logout"><a href="{{ url('log_out') }}">{{ gettext("Log Me Out") }}</a></li>
        {% else %}
        <li id="login"><a href="{{ url('registration:login') }}">{{ gettext("Log In / Register") }}</a></li>
        {% endif %}
        {% if user.is_staff %}
        <li id="admin"><a href="/admin" target="admin">{{ gettext("Admin Area") }}</a></li>
        {% endif %}
        {% if perms.webview.change_song %}
        <li id="menuqueue"><a href="{{ url('webview:uploads') }}">{{ gettext("Unapproved Uploads") }}</a> {{ dv.pending("songs")}}</li>
        {% endif %}
        {% if perms.webview.add_mute_oneliner %}
        <li id="menumute"><a href="{{ url('webview:muteoneliner') }}">{{ gettext("Mute account") }}</a></li>
        {% endif %}
        {% if user.is_staff %}
        <li></li>
        {% if perms.webview.change_artist %}
        <li id="unap-artists"><a href="{{ url('webview:newartists') }}">{{ gettext("Pending Artists") }}</a> {{ dv.pending("artists")}}</li>
        {% endif %}
        {% if perms.webview.change_group %}
        <li id="unap-groups"><a href="{{ url('webview:newgroups') }}">{{ gettext("Pending Groups") }}</a> {{ dv.pending("groups")}}</li>
        {% endif %}
        {% if perms.webview.change_compilation %}
        <li id="unap-compilations"><a href="{{ url('webview:newcompilations') }}">{{ gettext("Pending Compilations") }}</a> {{ dv.pending("compilations")}}</li>
        {% endif %}
        {% if perms.webview.change_label %}
        <li id="unap-labels"><a href="{{ url('webview:newlabels') }}">{{ gettext("Pending Labels") }}</a> {{ dv.pending("labels")}}</li>
        {% endif %}
        {% if perms.webview.change_screenshot %}
        <li id="unap-screenshots"><a href="{{ url('webview:newscreenshots') }}">{{ gettext("Pending Screenshots") }}</a> {{ dv.pending("screenshots")}}</li>
        {% endif %}
        {% if perms.webview.change_link %}
        <li id="unap-links"><a href="{{ url('webview:newlinks') }}">{{ gettext("Pending Links") }}</a> {{ dv.pending("links")}}</li>
        {% endif %}
        <li id="unap-nju"><a href="{{ url('webview:new-info') }}">{{ gettext("New info") }}</a> {{ dv.pending("info")}}</li>
        {% endif %}
      </ul>
    </div>

    <div id="nowplaying">
      <h3>{{ gettext("Currently Playing") }}</h3>
      <div data-name="nowplaying">
      {{ dv.current_song(user) }}
    </div>

    <hr style="width: 80%; background-color: #000; height: 1px; border: 0px;" />

    <input type="button" style="border: 1px solid; border-color: #333;" value="Listen" onclick="window.open('{{ url('webview:play_stream') }}','player','width=340,height=25,toolbar=no,scrollbars=no,resizable=no,location=no,directories=no,status=no,menubar=no,copyhistory=no')" /> - <a href="{{ url('webview:streams') }}">{{ gettext("Streams") }}</a>
  </div>

  <div id="sidebarnews">
    {% for item in dv.get_news("B") %}
    <div class="newsentryside">
      <h3 class="entrytitle">{{ item.title }}</h3>
      <div class="entrytext">{{ item.text }}</div>
    </div>
    {% endfor %}
    </div>
  </div>

  <div id="main">
    <h1 id="mainheader">{{ dv.site_name() }}</h1>
    <div id="mainlogo">{{ dv.logo() }}</div>

    <div style="overflow:auto" id="maincontent"{% block maindiv %}{% endblock %}>
    {% block main %}{% endblock %}
    </div>
  </div>

  <script>
  STATIC_URL = "{{ STATIC_URL }}";
  </script>
{% endblock %}

demovibes/templates/base/base_chat.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" {% block html %}id="base"{% endblock %}>
    <head>
        <link rel="stylesheet" href="{{ STATIC_URL }}themes/base.css" type="text/css" />
        <link rel="stylesheet" href="{{ STATIC_URL }}themes/chat.css" type="text/css" />
        <link rel="stylesheet" href="{{ dv.user_css(user) }}" type="text/css" />
        <link rel="icon" type="image/vnd.microsoft.icon" href="{{ STATIC_URL }}favicon.ico" />
        <title>{% block title %}{{ gettext("Welcome") }}{% endblock %} - {{ dv.site_name() }}</title>
        <meta name="Description" content="Demovibes Demoscene Radio - your 24/7 source of demoscene music" />
        <meta name="Keywords" content="demoscene, demo scene, scene music, scenemusic, radio, stream, streaming, demovibes, demo vibes, nectarine, necta" />
        {% block headblock %}{% endblock %}
        <script src="{{ STATIC_URL }}js/dutils.js" type="text/JavaScript"></script>
        <script src="{{ STATIC_URL }}js/dobject.js?1" type="text/JavaScript"></script>
        <script src="{{ STATIC_URL }}js/dtabcomplete.js" type="text/JavaScript"></script>
        <script src="{{ STATIC_URL }}js/sort/tablesort.min.js" type="text/JavaScript"></script>
        <script src="{{ STATIC_URL }}js/jquery.min.js" type="text/JavaScript"></script>
        <script src="{{ STATIC_URL }}js/jquery/popup.js" type="text/JavaScript"></script>
    </head>

    <body {% block bodyid %}id="site"{% endblock %} onload="ajaxmonitor({{ dv.ajaxevent() }});" onunload="ajaxmonitorabort();">
        {% block content %}{% endblock %}
    </body>
</html>

demovibes/templates/base/base_other.html
{% extends "base/base.html" %}
{% block sidebar %}
        <ul>
            <li id="home"><a href="{% url('webview:root') %}">{{ gettext("Home") }}</a></li>

            <li id="song-platform"><a href="{% url('webview:song-platform') %}">{{ gettext("Song Platforms") }}</a></li>
        </ul>
{% endblock %}

demovibes/templates/base/base_skeleton.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=1, viewport-fit=auto">
    <title>{% block title %}{{ gettext("Welcome") }}{% endblock %} - {{ dv.site_name() }}</title>
    {% block earlyheadblock %}{% endblock %}
    <link rel="stylesheet" href="{{ STATIC_URL }}themes/base.css?1" type="text/css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}themes/jquery.qtip.min.css" type="text/css" />
    <link rel="stylesheet" href="{{ dv.user_css(user)|e }}" type="text/css" />
    <script src="{{ STATIC_URL }}js/jquery.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/jquery.qtip.min.js?2" type="text/JavaScript"></script>
    <script src="{{ STATIC_URL }}js/dutils.js?1" type="text/JavaScript"></script>
    <script src="{{ STATIC_URL }}js/dobject.js?1" type="text/JavaScript"></script>
    <script src="{{ STATIC_URL }}js/dtabcomplete.js?1" type="text/JavaScript"></script>
    <script src="{{ STATIC_URL }}js/bbedit.js?1" type="text/JavaScript"></script>
    <script src="{{ STATIC_URL }}js/notification.js" type="text/JavaScript"></script>
    <script src="{{ STATIC_URL }}js/sort/tablesort.min.js" type="text/JavaScript"></script>
    <script src="{{ STATIC_URL }}js/jquery/popup.js" type="text/JavaScript"></script>
    {% include "base/extra_headers.html" %}
    {% block headblock %}{% endblock %}
  </head>

  <body {% block bodyid %}id="site"{% endblock %} tonload="ajaxmonitor({{ dv.ajaxevent() }});" tonunload="ajaxmonitorabort();">
    {% block content %}{% endblock %}
    {% include "base/page_footer.html" %}
  </body>
</html>

demovibes/templates/base/error.html
{% extends "base/base.html" %}

{% block main %}
<h2>{{ gettext("Error") }}</h2>
{{ error }}
{% endblock %}

demovibes/templates/base/extra_headers.html
<link rel="icon" type="image/vnd.microsoft.icon" href="{{ STATIC_URL }}no_favicon.ico" />
<meta name="Description" content="Cool radio" />
<meta name="Keywords" content="radio" />

demovibes/templates/base/page_footer.html
<footer>
  <span id="copyleft">
  Powered by <a href="https://framagit.org/demovibes/demovibes">Demovibes</a><br />
  </span>
  <span id="copyright">
  layout: <a href="http://raina.daug.net/">raina</a>,
  icons: <a href="http://www.famfamfam.com/"><span style="color: #f15;">fam</span><span style="color: #1cf;">fam</span><span style="color: #bf3;">fam</span></a>
  </span>
</footer>